INSERT INTO EVALUACION (FECHA_CREADA, ID_ESTADO_EVALUACION, ID_PLANTILLA, ID_REPRESENTANTE, ID_SUPERVISOR) VALUES ('2013-04-07', 1, 1, 4, 2);
INSERT INTO RESPUESTA (ID_EVALUACION, ID_PLANTILLA, ID_PUNTO_EVALUACION, CUMPLE_PUNTO) VALUES (2, 1, 1, 1);
INSERT INTO RESPUESTA (ID_EVALUACION, ID_PLANTILLA, ID_PUNTO_EVALUACION, CUMPLE_PUNTO) VALUES (2, 1, 2, 1);
INSERT INTO RESPUESTA (ID_EVALUACION, ID_PLANTILLA, ID_PUNTO_EVALUACION, CUMPLE_PUNTO) VALUES (2, 1, 3, 1);

INSERT INTO EVALUACION (FECHA_CREADA, ID_ESTADO_EVALUACION, ID_PLANTILLA, ID_REPRESENTANTE, ID_SUPERVISOR) VALUES ('2013-04-07', 1, 1, 4, 2);
INSERT INTO RESPUESTA (ID_EVALUACION, ID_PLANTILLA, ID_PUNTO_EVALUACION, CUMPLE_PUNTO) VALUES (3, 1, 1, 1);
INSERT INTO RESPUESTA (ID_EVALUACION, ID_PLANTILLA, ID_PUNTO_EVALUACION, CUMPLE_PUNTO) VALUES (3, 1, 2, 0);
INSERT INTO RESPUESTA (ID_EVALUACION, ID_PLANTILLA, ID_PUNTO_EVALUACION, CUMPLE_PUNTO) VALUES (3, 1, 3, 0);


INSERT INTO EVALUACION (FECHA_CREADA, ID_ESTADO_EVALUACION, ID_PLANTILLA, ID_REPRESENTANTE, ID_SUPERVISOR) VALUES ('2013-04-07', 1, 1, 5, 2);
INSERT INTO RESPUESTA (ID_EVALUACION, ID_PLANTILLA, ID_PUNTO_EVALUACION, CUMPLE_PUNTO) VALUES (4, 1, 1, 1);
INSERT INTO RESPUESTA (ID_EVALUACION, ID_PLANTILLA, ID_PUNTO_EVALUACION, CUMPLE_PUNTO) VALUES (4, 1, 2, 0);
INSERT INTO RESPUESTA (ID_EVALUACION, ID_PLANTILLA, ID_PUNTO_EVALUACION, CUMPLE_PUNTO) VALUES (4, 1, 3, 1);

INSERT INTO EVALUACION (FECHA_CREADA, ID_ESTADO_EVALUACION, ID_PLANTILLA, ID_REPRESENTANTE, ID_SUPERVISOR) VALUES ('2013-04-07', 1, 1, 5, 2);
INSERT INTO RESPUESTA (ID_EVALUACION, ID_PLANTILLA, ID_PUNTO_EVALUACION, CUMPLE_PUNTO) VALUES (5, 1, 1, 1);
INSERT INTO RESPUESTA (ID_EVALUACION, ID_PLANTILLA, ID_PUNTO_EVALUACION, CUMPLE_PUNTO) VALUES (5, 1, 2, 0);
INSERT INTO RESPUESTA (ID_EVALUACION, ID_PLANTILLA, ID_PUNTO_EVALUACION, CUMPLE_PUNTO) VALUES (5, 1, 3, 1);

